{% set name = "finlogic" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finlogic-{{ version }}.tar.gz
  sha256: f2fdd41e7b33c415df9aca481fb3994f3f875c0225e494145936bce2bc4c0e82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - numpy >=1.18.0
    - pandas >=1.4.0
    - python >=3.10
    - requests >=2.27.0
    - zstandard >=0.17.0

test:
  imports:
    - finlogic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crdcj/FinLogic
  summary: Finance toolkit for listed Brazilian companies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crdcj
