{% set name = "finlogic" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finlogic-{{ version }}.tar.gz
  sha256: 54fa5a7cfb9c278fbdbd0d1c72e41ce5cb14444b14c9ba67e3dfd3ca6ec2a84f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - numpy >=1.18.0
    - pandas >=1.4.0
    - python >=3.10
    - requests >=2.27.0
    - zstandard >=0.17.0

test:
  imports:
    - finlogic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crdcj/FinLogic
  summary: Finance toolkit for listed Brazilian companies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crdcj
