{% set name = "FinLogic" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 62a03180676bb4cc6f5f654910794495f827703053ddc117de161eb74a5dc4ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - pdm
  run:
    - python >=3.10
    - pandas >=1.4.0
    - requests >=2.27.0
    - zstandard >=0.17.0

test:
  imports:
    - finlogic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crdcj/FinLogic
  summary: Finance toolkit for listed Brazilian companies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crdcj
    - fe-lipe-c
