{% set name = "FinLogic" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 1b0e794e119f62919f75282b763a16780c5bf7345526078457f72d2c08401e92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - pdm-backend
  run:
    - python >=3.10
    - pandas >=1.4.0
    - requests >=2.27.0
    - zstandard >=0.17.0
    - duckdb >=0.7.0

test:
  imports:
    - finlogic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crdcj/FinLogic
  summary: Finance toolkit for listed Brazilian companies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crdcj
